services:
  # ========= BACKEND =========
  - type: web
    name: bt-taskboard-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    autoDeployTrigger: "off"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bt-taskboard-db
          property: connectionString

  # ========= FRONTEND (STATIC) =========
  - type: web
    name: bt-taskboard-web
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeployTrigger: "off"
    envVars:
      # Vite đọc biến này lúc build
      - key: VITE_API_URL
        sync: false

databases:
  - name: bt-taskboard-db
    plan: free
    databaseName: taskboard
    user: taskboard
